### ISSUE TITLE
MInimum Zoomlevel?

### ISSUE THREAD

**Issue by giggls** [BenjaminVadant/leaflet-ugeojson#11]
Is there an option to set a minimum zoomlevel required? While I would be able to do this on the server side, I would not consider this the best way to go.

And a second question. How would one bind an action to clicking an object in geojson layer?

Currently I have this very simple code:
http://camping.openstreetmap.de/map/

But these are the two things I would need to make it do what it should (besides a better web-design of course).

**Comment by BenjaminVadant** [comment]
Hi,
thank you for using my library.

Zoom level: currently, the library doesn't offer a way to discard a request based on the view information (x, y, z). This is an interesting idea though, one way to implement it is to add a parameter function that would define if a new request is necessary or not. 
Click on an object: as you point it out, the library is generating a geojson layer object. So everything that apply to geojson objects apply here too. Here is an example I found http://embed.plnkr.co/TcyDGH/ althought it is using a fairly old version of leaflet, I think it still apply.

If you would like to add the "validation function before request" (we need to come up with a better name) and create a pull request, I'd be happy to merge it.

Ben

**Comment by BenjaminVadant** [comment]
Thank you for your pull request, sorry about the delay.
