### ISSUE TITLE
disable geojson update

### ISSUE THREAD

**Issue by geologic** [BenjaminVadant/leaflet-ugeojson#13]
Hi

Is it possible to temporarily disable updating geojson layer when moving map?

I have lots of points that are loaded into map, sometimes i want to move map to another area but dont want to fetch and display points in between...

**Comment by BenjaminVadant** [comment]
Hi,

theoritically, the plugin should not load anything during motion as the event handler is called on "dragend", "zoomend" & "refresh" events (see https://github.com/BenjaminVadant/leaflet-ugeojson/blob/master/src/leaflet.uGeoJSON.js#L133)

I'll look into how to add it.

**Comment by BenjaminVadant** [comment]
I have added the "toggleDisabled" method that should meet your needs.

**Comment by geologic** [comment]
Great, it's perfect.
Thanks!
