### ISSUE TITLE
[QUESTION] Custom body

### ISSUE THREAD

**Issue by diegosanz** [BenjaminVadant/leaflet-ugeojson#9]
Hi! Nice plugin!
I need to make a custom request with a body like: `{"x": "42", "-y":"-2"}` but I can't achieve it. Can you give me some help?
Thanks!

**Comment by BenjaminVadant** [comment]
You should use the "parameters" option: https://github.com/BenjaminVadant/leaflet-ugeojson#how-to-use-the-parameters-option

**Comment by diegosanz** [comment]
I need those parameters dynamically, but by now I'm hardcoding them like this:
```
L.uGeoJSONLayer({
        endpoint: 'https://server/GetCoordinatesForPolygon',
        parameters: function () { return { "x": "42", "y": "-2" } } 
      })
```

but in my browser, on request payload I'm getting this:

```
------WebKitFormBoundaryvF0jiA9IydbAwY8N
Content-Disposition: form-data; name="south"

41.47154438707647
------WebKitFormBoundaryvF0jiA9IydbAwY8N
Content-Disposition: form-data; name="north"

41.881831370505594
------WebKitFormBoundaryvF0jiA9IydbAwY8N
Content-Disposition: form-data; name="east"

0.435333251953125
------WebKitFormBoundaryvF0jiA9IydbAwY8N
Content-Disposition: form-data; name="west"

-0.08514404296875001
------WebKitFormBoundaryvF0jiA9IydbAwY8N
Content-Disposition: form-data; name="zoom"

10
------WebKitFormBoundaryvF0jiA9IydbAwY8N--
```

Thank you for the fast response.

**Comment by BenjaminVadant** [comment]
You catch a mistake in the code!
It should now be fixed.

Thanks!

**Comment by diegosanz** [comment]
Thanks! Now it's working!
But I think that I catch another mistake or I'm doing something wrong: my server requires an 'application/json' enctype. I put `enctype: 'json'` on uGeoJSONLayer config, but the request still being `Content-Type: text/plain;charset=UTF-8`.
I made a hotfix writting: `request.setRequestHeader('Content-Type', 'application/json');` on line 119, just before i send it.
Is there any other way to do it?
because i've hard coded your code to achieve this.
Thanks

**Comment by BenjaminVadant** [comment]
Content type is set in headers so ... use the headers option! https://github.com/BenjaminVadant/leaflet-ugeojson#how-to-use-the-headers-option

**Comment by diegosanz** [comment]
My mistake! Now I have my application working, many many thanks!

**Comment by BenjaminVadant** [comment]
When you are done, can you send me a link to your application?

**Comment by diegosanz** [comment]
Sorry, my application it's for a top scret's FBI project.
Ha, ha, it's a joke, but it's for a private company than they want to visualize their properties and it's not a public app.
Anyway, I'm going to make a pull request to add one new feature soon ;)
